export const types = {
  authLogin: "[auth] Login",
  authLogout: "[auth] Logout",
  authJugar: "[auth] Jugar",
  authDejarDeJugar: "[auth] Dejar de jugar",
  authEntrarComoInvitado: "[auth] Entrar como invitado",
  mesasObtenerMesas: "[mesas] Obtener mesas",
  juegoRepartirCartas: "[juego] Repartir cartas",
  juegoTirarCarta: "[juego] Tirar carta",
  juegoCantarEnvido: "[juego] Cantar envido",
  juegoCantarTruco: "[juego] Cantar truco",
  juegoBloquearTurnos: "[juego] Bloquear turnos",
  juegoUsuariosConectados: "[juego] Usuarios conectados",
  juegoDejarMesa: "[juego] Dejar mesa",
  uiSetChantBox: "[ui] Set chant box",
  uiRemoveChantBox: "[ui] Remove chant box",
};
