export const types = {
  authLogin: "[auth] Login",
  authLogout: "[auth] Logout",
  authJugar: "[auth] Jugar",
  authDejarDeJugar: "[auth] Dejar de jugar",
  authEntrarComoInvitado: "[auth] Entrar como invitado",
  mesasObtenerMesas: "[mesas] Obtener mesas",
  juegoRepartirCartas: "[juego] Repartir cartas",
  juegoTirarCarta: "[juego] Tirar carta",
  juegoCantarEnvido: "[juego] Cantar envido",
  juegoCantarTruco: "[juego] Cantar truco",
  juegoBloquearTurnos: "[juego] Bloquear turnos",
  juegoUsuariosConectados: "[juego] Usuarios conectados",
  juegoDejarMesa: "[juego] Dejar mesa",
  juegoAsignarGanador: "[juego] Asignar ganador",
  uiSetChantBox: "[ui] Set chant box",
  uiRemoveChantBox: "[ui] Remove chant box",
  uiSetCargandoTrue: "[ui] Set cargando true",
  uiSetCargandoFalse: "[ui] Set cargando false",
  torneosObtenerTorneos: "[torneos] Obtener torneos",
  uiSetCargandoTrue2vs2: "[ui] Set cargando true 2vs2",
  uiSetCargandoFalse2vs2: "[ui] Set cargando false 2vs2",
  obtenerTorneoPartida: "[torneoPartidas] Obtener torneos partida"
};
